routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','User\HomeController@index');
Route::get('post','User\PostController@index')->name('post');

Route::get('admin/home', function () {
    return view('admin.home');
});


Route::post('post',function(){
    return view('user/post');
})->name('post');


Route::resource('admin/post','Admin\PostController');
Route::resource('admin/tag','Admin\TagController');
Route::resource('admin/category','Admin\CategoryController');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\category;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $categories = category::all();
      return view('admin.category.show',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.category.category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,[
        'name'=>'required',
        'slug'=>'required',
      ]);
      $category = new category;
      $category->name = $request->name;
      $category->slug = $request->slug;
      $category->save();
      return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $category = category::where('id',$id)->first();
      return view('admin.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request,[
        'name'=>'required',
        'slug'=>'required',
      ]);
      $category = category::find($id);
      $category->name = $request->name;
      $category->slug = $request->slug;
      $category->save();
      return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      category::where('id',$id)->delete();
      return redirect()->back();
    }
}

resources/views/admin/category/active.blade.php
@section('blogSection')
  <li class="nav-item has-treeview menu-open">
    <a href="#" class="nav-link active">
      <i class="nav-icon fas fa-blog"></i>
      <p>
        Blog
        <i class="right fas fa-angle-left"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">
      <li class="nav-item">
        <a href="{!! route('post.index') !!}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>Posts</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{!! route('category.index') !!}" class="nav-link active">
          <i class="far fa-circle nav-icon"></i>
          <p>Categories</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{!! route('tag.index') !!}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>Tags</p>
        </a>
      </li>
    </ul>
  </li>
@endsection

resources/views/admin/category/category.blade.php
@extends('admin.layouts.app')
@include('admin.category.active')
@section('main-content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><b>Create Category</b></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Category</a></li>
              <li class="breadcrumb-item active">Create</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <!-- Default card -->
      <div class="card">
        <div class="card-header with-border">


            <a class='col-lg-offset-5 btn btn-success' href="{{ route('category.index') }}">Back</a>

          <div class=" pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
            <form role="form" action="{!! route('category.store') !!}" method="post">
              @csrf

                @include('includes.messages')

                  <div class="form-group">
                    <label for="exampleInputEmail1">Category Title</label>
                    <input type="text" class="form-control" id="title" name="name" placeholder="Category title">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1"> Slug</label>
                    <input type="text" class="form-control" id="slug" name="slug" placeholder="Category slug">
                  </div>

              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>

          <!-- /.card -->
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>


@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.app')
@include('admin.category.active')
@section('main-content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><b>Add Category</b></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Category</a></li>
              <li class="breadcrumb-item active"></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default card -->
      <div class="card">
        <div class="card-header with-border">


            <a class='col-lg-offset-5 btn btn-success' href="{{ route('category.index') }}">Back</a>

          <div class=" pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
            <form role="form" action="{!! route('category.update',$category->id) !!}" method="post">
              @csrf
              {{method_field('PATCH')}}
                @include('includes.messages')

                  <div class="form-group">
                    <label for="exampleInputEmail1">Category Title</label>
                    <input type="text" class="form-control" value="{{$category->name}}" id="title" name="name" placeholder="Category title">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Category Slug</label>
                    <input type="text" class="form-control"  value="{{$category->slug}}"id="slug" name="slug" placeholder="Category slug">
                  </div>

              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>

          <!-- /.card -->
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>


@endsection

resources/views/admin/category/show.blade.php
@extends('admin.layouts.app')
@include('admin.category.active')
@section('headSection')
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><b>Categorys List</b></h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Tags</a></li>
            <li class="breadcrumb-item active"></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default card -->
    <div class="card">
      <div class="card-header with-border">


          <a class='col-lg-offset-5 btn btn-success' href="{{ route('category.create') }}">Add New</a>

          <div class=" pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
      </div>
      <div class="card-body">
                    <!-- /.card-header -->

                      <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                          <th>S.No</th>
                          <th>Tag Name</th>
                          <th>Slug</th>
                          <th>Edit</th>
                          <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $category)
                          <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->slug }}</td>
                              <td><a href="{{ route('category.edit',$category->id) }}"><span class="fa fa-edit"></span>  Edit</a></td>
                              <td>
                                <form id="delete-form-{{ $category->id }}" method="post" action="{{ route('category.destroy',$category->id) }}" style="display: none">
                                  {{ csrf_field() }}
                                  {{ method_field('DELETE') }}
                                </form>
                                <a href="" onclick="
                                if(confirm('Are you sure, You Want to delete this?'))
                                    {
                                      event.preventDefault();
                                      document.getElementById('delete-form-{{ $category->id }}').submit();
                                    }
                                    else{
                                      event.preventDefault();
                                    }" ><span class="fa fa-trash"></span> Delete</a>
                              </td>
                            </tr>
                          </tr>
                        @endforeach
                        </tbody>
                        <tfoot>

                        </tfoot>
                      </table>


      </div>

    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@section('footerSection')
<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
  $(function () {
    $("#example2").DataTable();
  });
</script>
@endsection