routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','User\HomeController@index');
Route::get('post','User\PostController@index')->name('post');

Route::get('admin/home', function () {
    return view('admin.home');
});


Route::post('post',function(){
    return view('user/post');
})->name('post');


Route::resource('admin/post','Admin\PostController');
Route::resource('admin/tag','Admin\TagController');
Route::resource('admin/category','Admin\CategoryController');

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\post;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $posts = post::all();
      return view('admin.post.show',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.post.post');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
          'title'=>'required',
          'subtitle'=>'required',
          'slug'=>'required',
          'body'=>'required',
        ]);
        $post = new post;
        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->slug = $request->slug;
        $post->body = $request->body;

        $post->image = $request->image;
        $post->save();


        return redirect(route('post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('admin.post.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $post = post::where('id',$id)->first();
      return view('admin.post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request,[
        'title'=>'required',
        'subtitle'=>'required',
        'slug'=>'required',
        'body'=>'required',
      ]);
      $post = post::find($id);
      $post->title = $request->title;
      $post->subtitle = $request->subtitle;
      $post->slug = $request->slug;
      $post->body = $request->body;

      $post->image = $request->image;
      $post->save();


      return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      post::where('id',$id)->delete();
      return redirect()->back();
    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
  public function index()
  {
    return view('user.post');
  }
}

resources/views/admin/post/active.blade.php
@section('blogSection')
  <li class="nav-item has-treeview menu-open">
    <a href="#" class="nav-link active">
      <i class="nav-icon fas fa-blog"></i>
      <p>
        Blog
        <i class="right fas fa-angle-left"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">
      <li class="nav-item">
        <a href="{!! route('post.index') !!}" class="nav-link active">
          <i class="far fa-circle nav-icon"></i>
          <p>Posts</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{!! route('category.index') !!}" class="nav-link ">
          <i class="far fa-circle nav-icon"></i>
          <p>Categories</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{!! route('tag.index') !!}" class="nav-link">
          <i class="far fa-circle nav-icon"></i>
          <p>Tags</p>
        </a>
      </li>
    </ul>
  </li>
@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.app')
@include('admin.post.active')
@section('main-content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><b>Edit Post</b></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Post</a></li>
              <li class="breadcrumb-item active">Edit</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="card">
        <div class="card-header with-border">

            <a class='btn btn-success' href="{{ route('post.index') }}">Back</a>
          <div class="pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">

            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{!! route('post.update',$post->id) !!}" method="post">
              @csrf
              {{method_field('PUT')}}
                @include('includes.messages')
                  <div class="form-group">
                    <label for="exampleInputEmail1">Post Title</label>
                    <input type="text" value="{{$post->title}}"class="form-control" id="title" name="title" placeholder="Title">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Post Sub Title</label>
                    <input type="text" value="{{$post->subtitle}}" class="form-control" id="subtitle" name="subtitle" placeholder="Sub Title">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Post Slug</label>
                    <input type="text" value="{{$post->slug}}" class="form-control" id="slug" name="slug" placeholder="Slug">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputFile">Image input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="image" value="{{$post->image}}" id="image" class="custom-file-input">
                        <label class="custom-file-label" for="image">Image</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                      </div>
                    </div>
                  </div>
                  <div class="form-check">
                    <input type="checkbox" name="status" @if($post->status == NULL)checked @endif class="" id="status">
                    <label class="form-check-label" value="{{$post->status}}" for="exampleCheck1">Status</label>
                  </div><br/>
                  <div class="forn-textarea">
                    <div class="mb-3">
                      <textarea id="editor1" name="body" style="width: 100%">{{$post->body}}</textarea>
                    </div>
                  </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>


@endsection
@section('footerSection')
  <script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>
  <!-- Bootstrap 4 -->

  <!-- CK Editor -->
  <script src="{{asset('admin/ckeditor/ckeditor.js')}}"></script>

  <!-- Bootstrap WYSIHTML5 -->

  <script>
      $(function () {
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('editor1');
      });
  </script>

@endsection

resources/views/admin/post/post.blade.php
@extends('admin.layouts.app')
@include('admin.post.active')
@section('headSection')
    <link rel="stylesheet" href="{{asset('admin/plugins/summernote/summernote-bs4.css')}}">

@endsection
@section('main-content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><b>Create Post</b></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Post</a></li>
              <li class="breadcrumb-item active">Create</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="card">
        <div class="card-header with-border">

            <a class='btn btn-success' href="{{ route('post.index') }}">Back</a>
          <div class="pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">

            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="{!! route('post.store') !!}" method="post">
              @csrf
                @include('includes.messages')
                  <div class="form-group">
                    <label for="exampleInputEmail1">Post Title</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Title">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Post Sub Title</label>
                    <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Sub Title">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Post Slug</label>
                    <input type="text" class="form-control" id="slug" name="slug" placeholder="Slug">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputFile">Image input</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="image" id="image" class="custom-file-input">
                        <label class="custom-file-label" for="image">Image</label>
                      </div>
                      <div class="input-group-append">
                        <span class="input-group-text" id="">Upload</span>
                      </div>
                    </div>
                  </div>
                  <div class="form-check">
                    <input type="checkbox" name="status" class="" id="status">
                    <label class="form-check-label" for="exampleCheck1">Status</label>
                  </div><br/>
                  <div class="card">
                    <div class="card-header">
                      <h3 class="card-title">Body</h3>

                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-widget="collapse">
                          <i class="fas fa-minus"></i>
                        </button>
                      </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                      <textarea class="textarea" name="body" placeholder="Place some text here"
                                style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
      </div>
      <!-- ./row -->
    </section>



@endsection
@section('footerSection')
  <!-- jQuery -->
  <script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <!-- FastClick -->
  <script src="{{asset('admin/plugins/fastclick/fastclick.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{asset('admin/dist/js/adminlte.min.js')}}"></script>
  <!-- Summernote -->
  <script src="{{asset('admin/plugins/summernote/summernote-bs4.min.js')}}"></script>

  <!-- Bootstrap WYSIHTML5 -->
  <script>
    $(function () {
      // Summernote
      $('.textarea').summernote()
    })
  </script>

@endsection

resources/views/admin/post/show.blade.php
@extends('admin.layouts.app')

@section('headSection')
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@include('admin.post.active')

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><b>Post List</b></h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Post</a></li>
            <li class="breadcrumb-item active"></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default card -->
    <div class="card">
      <div class="card-header border-0">


          <a class='col-lg-offset-5 btn btn-success' href="{{ route('post.create') }}">Add New</a>

        <div class=" pull-right card-tools">
          <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="card-body">
                    <!-- /.card-header -->

                      <table id="example1" class="table table-bordered table-striped">
                        <thead>
                           <tr>
                             <th>S.No</th>
                             <th>Title</th>
                             <th>Sub Title</th>
                             <th>Slug</th>
                             <th>Creatd At</th>
                             <th>Edit</th>
                             <th>Delete</th>

                           </tr>
                         </thead>
                         <tbody>
                         @foreach ($posts as $post)
                           <tr>
                             <td>{{ $loop->index + 1 }}</td>
                             <td>{{ $post->title }}</td>
                             <td>{{ $post->subtitle }}</td>
                             <td>{{ $post->slug }}</td>
                             <td>{{ $post->created_at }}</td>


                               <td><a href="{{ route('post.edit',$post->id) }}"><span class="fas fa-edit"></span> Edit</a> </td>



                             <td>
                               <form id="delete-form-{{ $post->id }}" method="post" action="{{ route('post.destroy',$post->id) }}" style="display: none">
                                 {{ csrf_field() }}
                                 {{ method_field('DELETE') }}
                               </form>
                               <a href="" onclick="
                               if(confirm('Are you sure, You Want to delete this?'))
                                   {
                                     event.preventDefault();
                                     document.getElementById('delete-form-{{ $post->id }}').submit();
                                   }
                                   else{
                                     event.preventDefault();
                                   }" ><span class="fas fa-trash"></span> Delete</a>
                             </td>

                           </tr>
                         @endforeach
                         </tbody>
                        <tfoot>

                        </tfoot>
                      </table>


      </div>

    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@section('footerSection')
<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
  $(function () {
    $("#example2").DataTable();
  });
</script>
@endsection