routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','User\HomeController@index');
Route::get('post','User\PostController@index')->name('post');

Route::get('admin/home', function () {
    return view('admin.home');
});


Route::post('post',function(){
    return view('user/post');
})->name('post');


Route::resource('admin/post','Admin\PostController');
Route::resource('admin/tag','Admin\TagController');
Route::resource('admin/category','Admin\CategoryController');

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\tag;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $tags = tag::all();

      return view('admin.tag.show',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.tag.tag');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,[
        'name'=>'required',
        'slug'=>'required',
      ]);
      $tag = new tag;
      $tag->name = $request->name;
      $tag->slug = $request->slug;
      $tag->save();
      return redirect(route('tag.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $tag = tag::where('id',$id)->first();
      return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, $id)
     {
       $this->validate($request,[
         'name'=>'required',
         'slug'=>'required',
       ]);
       $tag = tag::find($id);
       $tag->name = $request->name;
       $tag->slug = $request->slug;
       $tag->save();
       return redirect(route('tag.index'));
     }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      tag::where('id',$id)->delete();
      return redirect()->back();
    }
}

resources/views/admin/tag/active.blade.php
@section('blogSection')
  <li class="nav-item has-treeview menu-open">
    <a href="#" class="nav-link active">
      <i class="nav-icon fas fa-blog"></i>
      <p>
        Blog
        <i class="right fas fa-angle-left"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">
      <li class="nav-item">
        <a href="{!! route('post.index') !!}" class="nav-link ">
          <i class="far fa-circle nav-icon"></i>
          <p>Posts</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{!! route('category.index') !!}" class="nav-link ">
          <i class="far fa-circle nav-icon"></i>
          <p>Categories</p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{!! route('tag.index') !!}" class="nav-link active">
          <i class="far fa-circle nav-icon"></i>
          <p>Tags</p>
        </a>
      </li>
    </ul>
  </li>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('admin.layouts.app')
@include('admin.tag.active')
@section('main-content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><b>Add tag</b></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">tag</a></li>
              <li class="breadcrumb-item active"></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default card -->
      <div class="card">
        <div class="card-header with-border">


            <a class='col-lg-offset-5 btn btn-success' href="{{ route('tag.index') }}">Back</a>

          <div class=" pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
            <form role="form" action="{!! route('tag.update',$tag->id) !!}" method="post">
              @csrf
              {{method_field('PATCH')}}
                @include('includes.messages')

                  <div class="form-group">
                    <label for="exampleInputEmail1">tag Title</label>
                    <input type="text" class="form-control" value="{{$tag->name}}" id="title" name="name" placeholder="tag title">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">tag Slug</label>
                    <input type="text" class="form-control"  value="{{$tag->slug}}"id="slug" name="slug" placeholder="tag slug">
                  </div>

              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>

          <!-- /.card -->
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>


@endsection

resources/views/admin/tag/show.blade.php
@extends('admin.layouts.app')
@include('admin.tag.active')

@section('headSection')
<link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1><b>Tags List</b></h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Tags</a></li>
            <li class="breadcrumb-item active"></li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default card -->
    <div class="card">
      <div class="card-header with-border">


          <a class='col-lg-offset-5 btn btn-success' href="{{ route('tag.create') }}">Add New</a>

          <div class=" pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
      </div>
      <div class="card-body">
                    <!-- /.card-header -->

                      <table id="example1" class="table table-bordered table-striped">
                        <thead>
                          <tr>
                            <th>S.No</th>
                            <th>Title</th>
                            <th>Slug</th>
                            <th>Edit</th>
                            <th>Delete</th>
                          </tr>
                        </thead>
                        <tbody>
                         @foreach ($tags as $tag)
                           <tr>
                             <td>{{ $loop->index + 1 }}</td>
                             <td>{{ $tag->name }}</td>
                             <td>{{ $tag->slug }}</td>
                               <td><a href="{{ route('tag.edit',$tag->id) }}"><span class="fa fa-edit"></span> Edit</a></td>
                               <td>
                                 <form id="delete-form-{{ $tag->id }}" method="post" action="{{ route('tag.destroy',$tag->id) }}" style="display: none">
                                   @csrf
                                   {{ method_field('DELETE') }}
                                 </form>
                                 <a href="" onclick="
                                 if(confirm('Are you sure, You Want to delete this?'))
                                     {
                                       event.preventDefault();
                                       document.getElementById('delete-form-{{ $tag->id }}').submit();
                                     }
                                     else{
                                       event.preventDefault();
                                     }" ><span class="fa fa-trash"></span> Delete</a>
                               </td>
                             </tr>
                           </tr>
                         @endforeach
                         </tbody>
                        <tfoot>

                        </tfoot>
                      </table>


      </div>

    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@section('footerSection')
<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
  $(function () {
    $("#example2").DataTable();
  });
</script>
@endsection

resources/views/admin/tag/tag.blade.php
@extends('admin.layouts.app')
@include('admin.tag.active')
@section('main-content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><b>Add Tag</b></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Tag</a></li>
              <li class="breadcrumb-item active">Create</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default card -->
      <div class="card">
        <div class="card-header with-border">


            <a class='col-lg-offset-5 btn btn-success' href="{{ route('tag.index') }}">Back</a>

          <div class=" pull-right card-tools">
            <button type="button" class="btn btn-card-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-card-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
            <form role="form" action="{!! route('tag.store') !!}" method="post">
                @csrf

                @include('includes.messages')
                  <div class="form-group">
                    <label for="exampleInputEmail1">Tag Title</label>
                    <input type="text" class="form-control" id="title" name="name" placeholder="Tag title">
                  </div>

                  <div class="form-group">
                    <label for="exampleInputEmail1">Tag Slug</label>
                    <input type="text" class="form-control" id="slug" name="slug" placeholder="Tag slug">
                  </div>

              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>

          <!-- /.card -->
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>


@endsection